#!/bin/bash
#SBATCH --job-name=NANOGrav_tries_50
#SBATCH --output=/fred/oz002/vdimarco/sky_scrambles/skies/NANOGrav_tries_50.out
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --tmp=8g
#SBATCH --mem-per-cpu=8g

unset PYTHONPATH
ml conda
#module load anaconda3/2021.05

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/apps/skylake/software/Anaconda3/2021.05/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"             
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/apps/skylake/software/Anaconda3/2021.05/etc/profile.d/conda.sh" ]; then
#	. "/apps/skylake/software/Anaconda3/2021.05/etc/profile.d/conda.sh"
#    else
#	export PATH="/apps/skylake/software/Anaconda3/2021.05/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

conda activate ent15y             
#module use /apps/users/pulsar/common/modulefiles
#module use /apps/users/pulsar/skylake/modulefiles
#module load tempo2/0759584


python /fred/oz002/vdimarco/sky_scrambles/skies/NANOGrav_makeskyscrambles_val.py
